name: Check branch name

'on':
  push:
    branches-ignore:
      - develop
      - production

jobs:
  branch-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint branch name
        id: branch
        uses: AsasInnab/regex-action@v1
        with:
          regex_pattern: '^(refs/heads/INVESTO-[0-9]+)$'
          regex_flags: 'gm'
          search_string: '${{ github.ref }}'

      - name: Error branch name
        if: ${{ steps.branch.outputs.first_match == '' }}
        run: |
          echo ${{ github.ref }};
          echo 'Your branch name must be INVESTO-\d+';
          exit 1

      - name: Lint comment name
        id: comment
        uses: AsasInnab/regex-action@v1
        with:
          regex_pattern: '^((Merge)|(INVESTO-[0-9]+))'
          regex_flags: 'gm'
          search_string: '${{ github.event.head_commit.message }}'

      - name: Error comment head
        if: ${{ steps.comment.outputs.first_match == '' }}
        run: |
          echo ${{ github.event.head_commit.message }};
          echo 'Your comment must be started INVESTO-\d+';
          exit 1

  lint:
    runs-on: ubuntu-latest
    needs: branch-lint
    steps:
      - name: Getting the repo
        uses: actions/checkout@v3

      - name: Installing node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: npm install -f

      - name: Check prettier, lint scripts and styles
        run: npm run prettier-check && npm run lint
