name: Build android app

'on':
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Getting the repo
        uses: actions/checkout@v3

      - name: Installing node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: npm install -f


      - name: Clean android
        run: npm run clean-android

      - name: Build android
        env:
          KEYSTORE_ALIAS_PASSPHRASE: ${{ secrets.STAGING_KEYSTORE_ALIAS_PASSPHRASE }}
          KEYSTORE_ALIAS: ${{ secrets.STAGING_KEYSTORE_ALIAS }}
          KEYSTORE_PASSPHRASE: ${{ secrets.STAGING_KEYSTORE_PASSPHRASE }}
        run: |
          export VERSION_CODE=${{ github.run_number }}
          export VERSION_NAME=1.0.${{ github.run_number }}
          cd android && chmod +x ./gradlew && ./gradlew -PversCode=$VERSION_CODE -PversName=$VERSION_NAME app:assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          retention-days: 5
          path: 'android/app/build/outputs/apk/release/*.apk'

      - name: Post to a Slack channel
        uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: 'builds_app'
          slack-message: |
            GitHub build result: ${{ job.status }}
            The artifacts url is https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            -----------
            Description: ${{ github.event.head_commit.message }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
