name: 'Delete old artifacts'
on:
  schedule:
    - cron: '0 0 * * *' # every day in 0:00:00

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 5days # Set this to 0 to delete all artifacts